var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,h){a!=Array.prototype&&a!=Object.prototype&&(a[f]=h.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var f=0;return $jscomp.iteratorPrototype(function(){return f<a.length?{done:!1,value:a[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var f=a[Symbol.iterator];return f?f.call(a):$jscomp.arrayIterator(a)};
window.run=["$rootScope","$timeout","PeerService","IntegrationService",function(a,f,h,u){a.TILT_TERRAIN=window.TILT_TERRAIN;a.Math=Math;var v=!1,m=function(b){b&&alert(b);a.switchScreen("Title 0");h.disconnect();v=!0},w=function(){if(a.currentControls){for(var b=0,c=0,d=$jscomp.makeIterator(a.worlds),e=d.next();!e.done;e=d.next()){e=e.value;a.getWorldInfo(e).completed()&&c++;for(var k=$jscomp.makeIterator(a.getWorldInfo(e).levels()),g=k.next();!g.done;g=k.next())a.getLevelInfo(e,g.value).completed()&&
b++}u.max(a.currentControls+"WorldsComplete",c);u.max(a.currentControls+"LevelsComplete",b)}},r=function(){w();if(a.currentControls){var b={currentWorld:a.currentWorld,levelProgress:g},c=new Date;var d=c.getMonth()+1;var e=c.getDate(),k=c.getFullYear(),f=(c.getHours()+11)%12+1,h=c.getMinutes();10>h&&(h="0"+h);c=12<=c.getHours()?"PM":"AM";d=d+"/"+e+"/"+k+" at "+f+":"+h+" "+c;localStorage.setItem("jonrrich.tiltterrain.version",TILT_TERRAIN.version);localStorage.setItem("jonrrich.tiltterrain.time",d);
localStorage.setItem("jonrrich.tiltterrain.jet",a.currentJet);localStorage.setItem("jonrrich.tiltterrain."+a.currentControls,JSON.stringify(b));a.lastSaveTime=d}},t=function(){a.currentJet=localStorage.getItem("jonrrich.tiltterrain.jet")||1;a.lastSaveTime=localStorage.getItem("jonrrich.tiltterrain.time");if(a.currentControls){var b=JSON.parse(localStorage.getItem("jonrrich.tiltterrain."+a.currentControls))||{};a.currentWorld=b.currentWorld?b.currentWorld:1;if(b.levelProgress)g=b.levelProgress;else{g=
{};b=$jscomp.makeIterator(a.worlds);for(var c=b.next();!c.done;c=b.next()){c=c.value;g[c]={};for(var d=$jscomp.makeIterator(a.getWorldInfo(c).levels()),e=d.next();!e.done;e=d.next())g[c][e.value]={completeCount:0,failCount:0,progress:0}}}}};t();a.clearSave=function(){confirm("Deleting the save files cannot be undone. Are you sure?")&&(localStorage.removeItem("jonrrich.tiltterrain.tilt"),localStorage.removeItem("jonrrich.tiltterrain.keys"),localStorage.removeItem("jonrrich.tiltterrain.jet"),
localStorage.removeItem("jonrrich.tiltterrain.time"),t())};var g;a.switchScreen=function(b){v||(a.currentScreen="",f(function(){a.currentScreen=b},0))};a.currentScreen="Title 0";a.setControls=function(b){"tilt"==b?h.isConnected()?a.switchScreen("Title 2a"):(h.connect(),a.switchScreen("Title 1a")):"keys"==b&&(h.disconnect(),h.breakConnection(),a.switchScreen("Title 1b"));a.currentControls=b;t();w()};a.currentControls="";a.setCurrentWorld=function(b){a.currentWorld=b;r()};a.jets=[1,2,3,4,5];a.setJet=
function(b){a.currentJet=b;r()};var q=function(a,c){if("object"==typeof a)world=a.world,level=a.level;else if("string"==typeof a){var b=a.match(/W-(\d+)/);var e=a.match(/L-(\d+)/);b=b?parseInt(b[1]):null;e=e?parseInt(e[1]):null;world=b;level=e}else world=a,level=c;return{world:world,level:level}},n=function(a,c){var b=q(a,c);return"W-"+b.world+"_L-"+b.level},p=["Dunes","Arctic","Suburbia","Space"];a.worlds=p.map(function(a,c){return c+1});a.getWorldInfo=function(b){b=parseInt(b);return p[b-1]?{world:b,
prevWorld:function(){return 1==b?p.length:b-1},nextWorld:function(){return b==p.length?1:b+1},name:function(){return p[b-1]},levels:function(){return[1,2,3,4,5,6,7,8]},unlocked:function(){return a.getWorldInfo(b).levels().some(function(c){return a.getLevelInfo(b,c).unlocked()})},completed:function(){return a.getWorldInfo(b).levels().every(function(c){return a.getLevelInfo(b,c).completed()})}}:null};a.getLevelInfo=function(b,c){var d=q(b,c),e=d.world,k=d.level;d=a.getWorldInfo(e);var f=a.getWorldInfo(d.prevWorld()),
h=a.getWorldInfo(d.nextWorld());var l=d.levels()[d.levels().indexOf(k)-1]?n(e,d.levels()[d.levels().indexOf(k)-1]):n(d.prevWorld(),f.levels()[f.levels().length-1]);var m=d.levels()[d.levels().indexOf(k)+1]?n(e,d.levels()[d.levels().indexOf(k)+1]):n(d.nextWorld(),h.levels()[0]);return{world:e,level:k,levelString:function(){return n(e,k)},prevLevelString:function(){return l},nextLevelString:function(){return m},unlocked:function(){return 1==e&&1==k||a.getLevelInfo(l).completed()},completed:function(){return 0<
a.getLevelInfo(e,k).completeCount()},completeCount:function(){return g[e][k].completeCount},failCount:function(){return g[e][k].failCount},progress:function(){return g[e][k].progress}}};a.markLevelProgress=function(a,c,d){"undefined"==typeof d?(d=c,q(a)):q(a,c);100==d?g[world][level].completeCount+=1:g[world][level].failCount+=1;g[world][level].progress=Math.max(g[world][level].progress,d);r()};h.config({onConnect:function(){h.disconnect();f(function(){"tilt"==a.currentControls&&a.switchScreen("Title 2a")},
0)},heartbeatExpectation:2E3,onNoHeartbeat:function(){f(function(){"tilt"==a.currentControls&&(a.setControls("tilt"),alert("Controller unexpectedly disconnected. Please try to reconnect."))},0)},onError:function(a){switch(a.type){case "browser-incompatible":m("Sorry, your browser is outdated and does not support all of the features needed to use tilt controls. Please upgrade your browser or use the arrow key controls.");break;case "network":case "server-error":m("Couldn't connect to the server. Please check your internet connection and refresh.");
break;case "invalid-id":case "unavailable-id":m("Someone else is already using your pairing key. Please refresh and try again.");break;default:m("Something went wrong while trying to connect the controller. Please refresh and try again.")}}});var x=[38473,1698633989591,1386176414342,37456145,1542599249057,0xf9898341b9,2147239185795,37456145,0x7769db99274c2],l=function(){return x.shift().toString(36)};try{window[l()][l()][l()][l()](l())?0:m()}catch(b){window[l()][l()][l()](l())?0:m()}window.CanvasRenderingContext2D&&
localStorage||m("Sorry, your browser is outdated and does not support all of the features needed to run this game. Please upgrade your browser!");(!window.screen||!window.screen.width||!window.screen.height||800>window.screen.width||600>window.screen.height)&&m("Your computer screen is too small! At least 800 x 600 pixels is required.")}];
